<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyVersion>3.0.0</AssemblyVersion>
    <FileVersion>3.0.0</FileVersion>
    <Version>3.0.0</Version>
    <Title>Spatial Trees</Title>
    <Authors>Roger_Hill</Authors>
    <Company>Global Conquest Games</Company>
    <Description>Spatial Trees - a set of fast quadtree and octree implimentations 
for gaming and simulations. An OS library tuned for speed.</Description>
    <Copyright>Copyright 2017, Roger Hill </Copyright>
    <PackageProjectUrl>https://github.com/hroger1030/SpatialTrees</PackageProjectUrl>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PackageTags>games;performance;octree;quadtree;collision detection</PackageTags>
    <PackageReleaseNotes>Update to .net10, plus major speed tuning</PackageReleaseNotes>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastG" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
